<a href="https://colab.research.google.com/github/pranay-aggarwal/Minor-Project./blob/main/Minor_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bing_image_downloader

In [ ]:
!pip install streamlit
!pip install pyngrok


In [ ]:
!mkdir images

mkdir: cannot create directory ‘images’: File exists


In [ ]:
from bing_image_downloader import downloader
downloader.download('cats',limit=30,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/cats


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://miaustore.com/uk/wp-content/uploads/sites/3/2018/04/sad-cat.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://cdn.shortpixel.ai/client/q_lossy,ret_img,w_1000/https://www.ukpets.com/blog/wp-content/uploads/2018/05/cat.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/originals/12/c8/4f/12c84fafbc0853a92326a312e0754452.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/6d/2d/02/6d2d02a6860d3f0ed30ea159f5c3cdf0.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://klyker.com/wp-content/uploads/2014/10/hellish-cats-32.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/2a/e3/73/2ae3735fe748d8de127670dc71d39cf1.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://getesa.com/img/articles/cats-as-emotional-support-a

In [ ]:
downloader.download('dogs',limit=30,output_dir='images',adult_filter_off=True)

[%] Downloading Images to /content/images/dogs


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from http://englishrussia.com/wp-content/uploads/2015/04/516.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/47/c7/63/47c7632aa28132d90e150805df317cf8.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://img2.grunge.com/img/gallery/false-facts-about-dogs-you-always-thought-were-true/dogs-and-cats-just-cant-get-along.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/8c/55/d8/8c55d878ab9d1e83642f355b0b53d782.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://englishrussia.com/wp-content/uploads/2015/04/1114.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://englishrussia.com/wp-content/uploads/2015/04/532.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://englishrussia.com/wp-content/uploads/2015/04/515.jpg
[%] File Downloaded !



In [ ]:
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn.metrics import accuracy_score,confusion_matrix
import pickle
from pyngrok import ngrok
import streamlit as st

In [ ]:
target=[]
images=[]
flat_data=[]

DATADIR= '/content/images'
CATEGORIES=['cats','dogs']



In [ ]:
for category in CATEGORIES:
    class_num=CATEGORIES.index(category)
    path=os.path.join(DATADIR,category)
    for img in os.listdir(path):
       img_array=imread(os.path.join(path,img))
       img_resized=resize(img_array,(150,150,3))
       flat_data.append(img_resized.flatten())
       images.append(img_resized)
       target.append(class_num)

flat_data=np.array(flat_data)
target=np.array(target)
images=np.array(images)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(flat_data,target,test_size=0.3,random_state=109)

In [ ]:
param_grid= [
             {'C':[1.0,10.0,100.0,1000.0],'gamma':[0.001,0.0001],'kernel':['rbf']},
              {'C':[1.0,10.0,100.0,1000.0],'kernel':['linear']},
]

svc=svm.SVC(probability=True)
clf=GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1.0, 10.0, 100.0, 1000.0],
                          'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
                         {'C': [1.0, 10.0, 100.0, 1000.0],
                          'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
y_pred=clf.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1])

In [ ]:
y_test

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1])

In [ ]:
accuracy_score(y_pred,y_test)

0.5409836065573771

In [ ]:
confusion_matrix(y_pred,y_test)

array([[23, 19],
       [ 9, 10]])

In [ ]:
pickle.dump(clf,open('img_model.p','wb'))
model=pickle.load(open('img_model.p','rb'))
flat_data=[]
url=input('enter your url of image: ')
img= imread(url)
img_resize=resize(img,(150,150,3))
flat_data.append(img_resize.flatten())
flat_data=np.array(flat_data)
print(img.shape)
y_out=model.predict(flat_data)
y_out=CATEGORIES[y_out[0]]
print(f' predicted output: {y_out} ')  

enter your url of image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfx__RoRYzLDgXDiJxYGxLihJC4zoqV3V0xg&usqp=CAU.jpg
(198, 255, 3)
 predicted output: dogs 


In [ ]:
%%writefile app.py  
import streamlit as st
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pickle
from PIL import Image
st.title('Image Classifier- Cats or Dogs')
st.text('upload the image')
model=pickle.load(open('img_model.p','rb'))
uploaded_file =st.file_uploader('choose an image...',type='jpg')
if uploaded_file is not None:
    img=Image.open(uploaded_file)
    st.image(img,caption'uploaded file')
if st.button('PREDICT'):
    CATEGORIES=['cats','dogs']
    st.write('result.....')
    flat_data=[]
    img=np.array(img)
    img_resize=resize(img,(150,150,3))
    flat_data.append(img_resize.flatten())
    flat_data=np.array(flat_data)
    y_out=model.predict(flat_data)
    y_out=CATEGORIES[y_out[0]]
    st.title(f' predicted output: {y_out} ')
    q=model.predict_proba(flat_data)
    for index,item in enumerate(CATEGORIES):
        st.write(f'{item}:{q[0][index]*100%}')

Overwriting app.py


In [ ]:
!nohup streamlit run app.py &
 
url=ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


2021-06-12 12:14:22.927 INFO    pyngrok.ngrok: Opening tunnel named: http-80-fcbf58cf-c8c6-4ef9-9fd0-b9180fe406f6
2021-06-12 12:14:22.991 INFO    pyngrok.process.ngrok: t=2021-06-12T12:14:22+0000 lvl=info msg="no configuration paths supplied"
2021-06-12 12:14:22.994 INFO    pyngrok.process.ngrok: t=2021-06-12T12:14:22+0000 lvl=info msg="using configuration at default config path" path=/root/.ngrok2/ngrok.yml
2021-06-12 12:14:22.999 INFO    pyngrok.process.ngrok: t=2021-06-12T12:14:22+0000 lvl=info msg="open config file" path=/root/.ngrok2/ngrok.yml err=nil
2021-06-12 12:14:23.001 INFO    pyngrok.process.ngrok: t=2021-06-12T12:14:22+0000 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
2021-06-12 12:14:23.113 INFO    pyngrok.process.ngrok: t=2021-06-12T12:14:23+0000 lvl=info msg="tunnel session started" obj=tunnels.session
2021-06-12 12:14:23.115 INFO    pyngrok.process.ngrok: t=2021-06-12T12:14:23+0000 lvl=info msg="client session established" obj=csess id=1d6f5057d46d
2

<NgrokTunnel: "http://b27595c979b7.ngrok.io" -> "http://localhost:80">

2021-06-12 12:14:23.188 INFO    pyngrok.process.ngrok: t=2021-06-12T12:14:23+0000 lvl=info msg=end pg="/api/tunnels/http-80-fcbf58cf-c8c6-4ef9-9fd0-b9180fe406f6 (http)" id=b091d9be67bf86b2 status=200 dur=183.994µs


In [ ]:
##sample images
#https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfx__RoRYzLDgXDiJxYGxLihJC4zoqV3V0xg&usqp=CAU.jpg
#https://specials-images.forbesimg.com/imageserve/6082931ef598a85b055afe77/960x0.jpg?cropX1=0&cropX2=3475&cropY1=182&cropY2=2137.jpg